export const skills = ["React", 
"Javascript", 
"Java",
"SpringBoot", 
"C and C++",
"C#", 
"Python",
"Elixir",
"Elixir Phoenix", 
"UI/UX Tools", 
"Unix/Linux",
"TCP/IP and general network programming",
"SQL", 
"NoSQL"];